import numpy as np
array = np.arange(1,5).reshape(2,2)
print(array)

a = np.repeat(2,4).reshape(2,-1)
print(a) 
print("") 
b = np.repeat(1,4).reshape(2,-1)
print(b)
print("") 
c = np.vstack([a,b])
print(c)
print("")
d = np.hstack([a,b])
print(d)
print("")    
e = np.dot(a,b)
print(e)
print("")
f = np.sum(e)
print("the sum is:",f)